### ISSUE TITLE
Compatibility with Trino

### ISSUE THREAD

**Issue by VitaliyMF** [bamcis-io/PrestoClient#14] opened 2021-09-28 11:50 UTC
Starting from Trino 351 client protocol headers were renamed as mentioned here ("X-Trino" instead of "X-Presto"): https://trino.io/docs/current/release/release-351.html

I think it is good idea to have an option in PrestoClientSessionConfig like "TrinoMode" or something like that. It is still unclear if that's enough to be compatible with Trino, I'll try to do more investigation here.

**Comment by hakenmt** [comment] 2021-09-28 13:19
Someone else also opened this same issue and offered to create a PR to address, but hasn't done so yet. From the release notes, you can still support legacy clients, "Legacy clients can be supported by setting the configuration property protocol.v1.alternate-header-name to Presto".

Each version of this client was targeted at a specific version of Presto since object properties, types, values all change. This was intended to provide as complete of parsing of json as possible. So, this change would introduce a new version of the client to start supporting version 351 and beyond. Again, open to this update, but I don't have the bandwidth to research all of the changes that would be needed to bring the client up to parity with all of the changes in version 351.

**Comment by hakenmt** [comment] 2021-09-28 15:17
Here's an update that allows you to specify whether you use the legacy headers or new headers in the `PrestoClientSessionConfig`. It will default to setting `EnableLegacyHeaderCompatibility` to false and use the X-Trino- header prefix. I have not tested this and there may be other configurations that are need to work with version 351, but the headers should be set correctly. Please test and provide feedback. This is a link to the nuget package you can use for testing.

https://github.com/bamcis-io/PrestoClient/releases/tag/0.351.0-beta

**Comment by VitaliyMF** [comment] 2021-09-29 06:19
@hakenmt thank you for a quick response!

I've tried 0.351.0-beta with [trinodb/trino](https://hub.docker.com/r/trinodb/trino) docker image and with X-Trino headers was able to connect and execute, at least, some simple queries for 'tpcds' catalog (it is included in this image). I'm using "PrestoClient" as a connector in my BI tool [SeekTable](https://www.seektable.com) and for this purpose I've implemented my [ADO.NET provider based on "PrestoClient"](https://github.com/nreco/presto-ado).  I hope it will work for both PrestoDB (as it is not abandoned as I understand -- Trino is a fork) and TrinoDB, and for other Presto REST-API compatible endpoints -- in particular, MetriQL (for this one even version 0.198.5 works like a charm).

It would be nice if you'll publish 0.351-beta on nuget too. 

Not a big deal, maybe it makes sense to evaluate headers in `ProtocolHeaders` class in a constructor (instead of getters like `public string REQUEST_USER => $"{this.prefix}User";`), and use singletons for Presto/Trino headers in `PrestodbClient` instead of ProtocolHeaders creation each time:

```
        private ProtocolHeaders GetProtocolHeaders()
        {
            return new ProtocolHeaders(this.Configuration.EnableLegacyHeaderCompatibility ? "Presto" : "Trino");
        }
```

Also I think it is better to leave "Presto" headers by default (after all, the package is named "PrestoClient" and Presto is much more recognizable than Trino at least for now), and switch to "Trino" headers by the option.

Again, thanks a lot for your efforts!

**Comment by VitaliyMF** [comment] 2022-09-10 07:30
@hakenmt are you planning to publish "vNext" (0.351.0-beta) on nuget.org? If not, could you confirm that this repo is no longer maintained (Trino widely used now) and it makes sense to make a fork and publish "vNext" as a separate nuget package?

**Comment by naushadh** [comment] 2022-09-13 18:58
I too would like to see vNext released. If the hold up is a matter testing the branch I've got a PR opened to automate that.

Related to forks, it appears some created https://github.com/jcapellman/PrestoNET as a fork of this project.

**Comment by hakenmt** [comment] 2022-09-13 19:20
I can certainly push the current 0.351.0-beta version to nuget. I'm not really actively maintaining this repo anymore, so I don't have a good test environment. I see the PR for that, which also identifies some other failures. I'll review the PRs and see if I can merge them.

**Comment by naushadh** [comment] 2022-09-21 14:04
Hey @hakenmt, just following up on this. I'd appreciate it if you could release `0.351.0-beta` to Nuget as the project I'm currently working on is blocked until then.

**Comment by hakenmt** [comment] 2022-09-23 15:22
I've added that package to nuget, you should see it appear shortly. It is the existing package posted here and does not resolve some of the issues identified in the PRs. I'm going to close this issue and review the PRs separately.

**Closed by hakenmt** 2022-09-23 15:22 UTC
